apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/namespace.yaml
  - platform/postgres.yaml
  - platform/prometheus.yaml
  - platform/rbac.yaml
  - platform/application.yaml
  - fixtures/workloads.yaml
